### Prueba sin API key (debe fallar)
GET http://127.0.0.1:8088/health

### Prueba con API key (debe funcionar)
GET http://127.0.0.1:8500/health
x-api-key: supersecreta123
### Buscar suscriptor inexistente (debe dar 404)
GET http://localhost:8500/live/usuarioprueba
x-api-key: Zo9fUbuGS5QhJUi8k4zvydAOrHBcBsZx9vz67Woy4Bk9PVSql1rjycpoI2yrajd8
### Buscar suscriptor de prueba (debe dar 200)
GET http://127.0.0.1:8500/diagnosis/acastro
x-api-key: Zo9fUbuGS5QhJUi8k4zvydAOrHBcBsZx9vz67Woy4Bk9PVSql1rjycpoI2yrajd8

### probar produccion
GET http://138.59.172.24:8500/diagnosis/acastro
x-api-key: Zo9fUbuGS5QhJUi8k4zvydAOrHBcBsZx9vz67Woy4Bk9PVSql1rjycpoI2yrajd8

###

GET http://138.59.172.24:8500/live/mdlujan
x-api-key: Zo9fUbuGS5QhJUi8k4zvydAOrHBcBsZx9vz67Woy4Bk9PVSql1rjycpoI2yrajd8


@host = http://127.0.0.1:8500
@apikey = Zo9fUbuGS5QhJUi8k4zvydAOrHBcBsZx9vz67Woy4Bk9PVSql1rjycpoI2yrajd8

### 1. Health Check (Verificar que el servicio responde)
GET {{host}}/health
x-api-key: {{apikey}}

### 2. BÚSQUEDA: Por Nombre (Cliente administrativo)
# Debería traer datos de la tabla 'clientes' + 'connections'
GET {{host}}/search?q=Juan
x-api-key: {{apikey}}

### 3. BÚSQUEDA: Por Dirección (Cliente administrativo)
# Prueba buscar una calle común
GET {{host}}/search?q=San Martin
x-api-key: {{apikey}}

### 4. BÚSQUEDA: Por PPPoE Parcial (Híbrido)
# Prueba poner parte de un usuario. Debería traer coincidencias de ambas tablas.
GET {{host}}/search?q=usuario
x-api-key: {{apikey}}

### 5. BÚSQUEDA: "Solo Técnico" (Cliente Huérfano)
# Escribe un SN o un usuario PPPoE que sepas que está en la OLT pero NO en el sistema.
# Debería devolver origen: "smartolt" y nombre: "Solo en OLT"
GET {{host}}/search?q=HWTCE
x-api-key: {{apikey}}

### 6. DIAGNÓSTICO: Cliente Completo
# Un usuario que existe en ISPCube.
GET {{host}}/diagnosis/usuarioprueba
x-api-key: {{apikey}}

### 7. DIAGNÓSTICO: Cliente Huérfano (Solo Técnico)
# Un usuario que solo existe en el Mikrotik/OLT.
# Debería traer datos de señal/ONU aunque diga "Cliente no encontrado" en datos comerciales.

GET {{host}}/live/usuarioprueba
x-api-key: {{apikey}}
###
GET {{host}}/diagnosis/usuario_solo_tecnico
x-api-key: {{apikey}}
